# Generated by Django 6.0.6 on 2026-06-22 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeismicReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField()),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('well_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governance.welltarget')),
            ],
        ),
        migrations.CreateModel(
            name='TargetApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('approval_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField()),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('well_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governance.welltarget')),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid')], max_length=20)),
                ('validation_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField()),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('well_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governance.welltarget')),
            ],
        ),
        migrations.CreateModel(
            name='WellTargetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('well_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governance.welltarget')),
            ],
        ),
        migrations.CreateModel(
            name='WellTargetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('remarks', models.TextField()),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('well_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governance.welltarget')),
            ],
        ),
    ]
