# Generated by Django 6.0.6 on 2026-07-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0004_create_demo_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=150)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
