# Generated by Django 6.0.6 on 2026-07-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0005_administratoraccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='administratoraccessrequest',
            name='identification_document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/admin_requests/documents/'),
        ),
        migrations.AddField(
            model_name='administratoraccessrequest',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('COMPANY_BADGE', 'Company ID Badge'), ('NATIONAL_ID', 'National ID Card'), ('PASSPORT', 'Passport'), ('DRIVERS_LICENSE', "Driver's License"), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='administratoraccessrequest',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/admin_requests/photos/'),
        ),
        migrations.AddField(
            model_name='administratoraccessrequest',
            name='review_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='administratoraccessrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
