# Generated by Django 6.0.6 on 2026-07-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0006_administratoraccessrequest_identification_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administratoraccessrequest',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='administratoraccessrequest',
            name='company_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='administratoraccessrequest',
            name='home_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='administratoraccessrequest',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='administratoraccessrequest',
            name='office_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
