# Generated by Django 6.0.6 on 2026-07-22 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0008_businessunit_company_country_department_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PROJECT_MANAGER', 'Project Manager'), ('LEAD_INTERPRETER', 'Lead Interpreter'), ('REVIEWER', 'Reviewer'), ('VALIDATOR', 'Validator'), ('APPROVER', 'Approver'), ('TEAM_MEMBER', 'Team Member')], max_length=30)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='governance.project')),
            ],
            options={
                'unique_together': {('project', 'employee')},
            },
        ),
    ]
