# Generated by Django 6.0.6 on 2026-07-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0009_projectteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seismicreview',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
