# Generated by Django 6.0.6 on 2026-07-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0010_alter_seismicreview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=20),
        ),
    ]
